### PR TITLE
makefile serial/parallel usage

### PR DESCRIPTION
**Pull request by vamartid**
Probably the "single core" folder is not needed now makefile builds both from the same code.
Results from the make file version need to be compared with the "single core" folder to be sure.

### CODE REVIEW

**Comment by vamartid** [comment]
handles issue  #9

**Comment by drazioti** [comment]
[1] After 
`$make serial`
and
```
$ ./carmichael.out 5 4 4 3 2 1 1 --ham 15 -b 32 -f 1 -q 10

I got 
....
....
....

Del set made 
!!!!!!!!FOUND INTERSECTION!!!!!!!!
Total program time : 18061847.000000
Carmichael number stored now terminating...

```
It seems that there is something wrong with the time.

[2] It seems that parallel is not in fact parallel. It uses only one core.

**Comment by vamartid** [comment]
what is the output of "make all" or 
of "make serial" and "make parallel" individually?

**Comment by drazioti** [comment]
> what is the output of "make all" or
> of "make serial" and "make parallel" individually?

carmichael.out, carmichael_par.out. Δες τα αλλα δύο σχόλια που εχω. Τελικα παιζει το παραλληλο.

**Comment by drazioti** [comment]
νομίζω ότι το single core μετραει μονο το intersection time και όχι το συνολικο χρόνο (δηλ. και το χρόνο για αποθηκευση του P_set)

**Pull request merged**
