### PR TITLE
Fixed most bugs with inverse modulo and all seg faults

### PR DESCRIPTION
**Pull request by etiganou**

### CODE REVIEW

**Comment by drazioti** [comment]
`./a.out 40 39 38 1 1 --ham 15 -b 32 -f 1`

```
values : 40 39 38 1 1 
Bound : 32
Fragmentation : 1
Lambda is : 124818698712984465874893716083283958827305735281288532721664
hamming   : 15
P size is : 15863
looking for Carmichaels with 15848 factors

density of the problem     : 81.748318

Size of I is : 32
h1 = 7
h2 = 8
Hash Implementation: True
......
Number 102464604362751399936000000000000000001 doesnt have inverse modulo 124818698712984465874893716083283958827305735281288532721664
```
again we have the inverse modulo. Also I  noticed that sagemath provides a different Lambda, 124818698712984469023600000000000000000000000000000000000000 

and a different number of P_set, 17062.

**Comment by drazioti** [comment]
issued #16 does not resolved. Check onn your own,

**Comment by drazioti** [comment]
When all the previous solved, please only then send a new pull request.

**Comment by etiganou** [comment]
Fixed bugs on inverse modulo and P_set

**Comment by drazioti** [comment]
As far as issue #16 I got the same error. Add [WIP] in the title of your pull request.

**Comment by etiganou** [comment]
I dont have this error anymore

**Comment by drazioti** [comment]
try `$git log`
My head is in the commit:
commit 76d907fc5ef2544b0a3490322d24653f0f2f228b 
What do you get?

**Comment by etiganou** [comment]
This is the last commit the problem should be solved... One commit before that I changed the code in parallel version that caused the problems

**Comment by etiganou** [comment]
61f1ab9 this solved the problem

**Comment by drazioti** [comment]
the last pull you've made agrees with mine not your local commitment. So you have to push and pull again!

**Comment by etiganou** [comment]
έκανα pull

**Comment by etiganou** [comment]
This input runs correctly on my code

**Comment by etiganou** [comment]
να κλείσω μήπως αυτό το pull request και να το ξανακάνω ?

**Comment by drazioti** [comment]
show me the output of` ./a.out 40 39 38 1 1 --ham 15 -b 32 -f 1`
(and no, stay in this pull request)

**Comment by drazioti** [comment]
The output 
Number 3235799124554918962530791759490966796876 doesnt have inverse modulo 124818698712984469023600000000000000000000000000000000000000

is true in the sense that indeed the two numbers have gcd > 1, so there is not an inverse. 
This is another type of problem, not accuracy problem.

**Comment by drazioti** [comment]
> This input runs correctly on my code

show me the output of ./a.out 40 39 38 1 1 --ham 15 -b 32 -f 1

**Comment by drazioti** [comment]
> να κλείσω μήπως αυτό το pull request και να το ξανακάνω ?

no

**Comment by etiganou** [comment]
Output του παραδείγματος 

Screenshot from 2020-02-11 21-10-34

μετα συνεχίζει να τρέχει κανονικά

**Comment by etiganou** [comment]
Σας λείπει αυτή η γραμμη κώδικα 
Screenshot from 2020-02-11 21-14-33

γραμμές 155-157 στο carmi.cpp

**Comment by drazioti** [comment]
> Output του παραδείγματος
> 
> Screenshot from 2020-02-11 21-10-34
> 
> μετα συνεχίζει να τρέχει κανονικά
why you sent a screenshot? copy and paste the output.Maybe you have to wait a little to see the problem. The problem appears after The U1 has been built.

**Comment by drazioti** [comment]
> Σας λείπει αυτή η γραμμη κώδικα
> Screenshot from 2020-02-11 21-14-33
> 
> γραμμές 155-157 στο carmi.cpp

no I have this line. we run the same code.

**Comment by drazioti** [comment]
Ok got it.

**Comment by drazioti** [comment]
Only issue #7 remains,

**Pull request merged**
