### PR TITLE
Fixed I randomization

### PR DESCRIPTION
**Pull request by etiganou**
Fixed the non-random I1, I2. I dont know how this problem came up we solved this a long time ago...
This most probably fixes the repeating hashes

### CODE REVIEW

**Comment by etiganou** [comment]
This resolves #28 #26 #7

**Comment by drazioti** [comment]
I think that the problem did not solved. Executing
`./a.out 10 5 4 2 1 --ham 12 -b 20 -f 1`
I always get in the 7th round the solution.

**Comment by etiganou** [comment]
OK I forgot to change smthing... now is working properly

**Comment by drazioti** [comment]
> OK I forgot to change smthing... now is working properly

Are you sure that is working properly, because I got exactly the same result.

**Comment by etiganou** [comment]
yes I_set changes in every round i checked it

**Comment by drazioti** [comment]
> yes I_set changes in every round i checked it

Why I found every time in the same round the solution? I do not expect this, if I_1,I_2 are different in every round and every execution of the program

**Comment by etiganou** [comment]
Thats not happening to me

**Comment by drazioti** [comment]
yes, I forgot to recompile!

**Comment by drazioti** [comment]
I suppose this solves the problem with the repeating hash values

**Pull request merged**
